title: SkyBlog
markdown: kramdown

# for atom feed
author:
  name: Sebastian Joerz
  email: sjoerz@skyface.de

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: "_projects"
    values:
      layout: "project"
      permalink: /projects/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
